### ISSUE TITLE
Unsecue parts of page

### ISSUE THREAD

**Issue by Marcus-Nightingale** [YourZero/YourLeague#9]
Yo. Change L16 on profile.blade.php from 

`<img src="http://ddragon.leagueoflegends.com/cdn/9.9.1/img/profileicon/{{$summoner->profileIconId}}.png"/>`

to 

`<img src="https://ddragon.leagueoflegends.com/cdn/9.9.1/img/profileicon/{{$summoner->profileIconId}}.png"/>`

**Comment by YourZero** [comment]
This has been resolved by a commit a week ago
